# Generated by Django 6.1 on 2026-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('ADMIN', 'Administrador'), ('EVALUADOR', 'Evaluador')], default='ESTUDIANTE', max_length=20, verbose_name='Rol'),
        ),
    ]
